services:
  nightingale:
    image: ghcr.io/ekman/nightingale:1
    build:
      context: .
    restart: unless-stopped
    read_only: true
    volumes:
      - "./config/Config:/home/steam/game/NWX/Config:ro"
      - "./config/Saved:/home/steam/game/NWX/Saved"
      - "./game:/home/steam/game"
    expose:
      - 8211:8211/udp
      - 8888:8888
    environment:
      - NAME=Foo
